title: My Tech Journey Blog
author: Jaime Bacon
email: romans18@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  35 years old and looking to transition into an Information Technology career. This is how I will catalog my journey, I hope you will join me
  as I explore the exciting field of Information Technology, Web Development, Programming, Networking and more.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  baconj # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
# theme
theme: minima
